### ISSUE TITLE
Request: Allow list of schema to be validated against

### ISSUE THREAD

**Issue by CD3** [nicolaiarocci/cerberus#108]
It would be useful to allow the `schema` key and  to be a list, which would be interpreted as a set of possible schemas that should be applied and the entry should validate if any of the schemas validate. It is already possible to give a list of types, but if I want to make sure that a value is a dict that has one of two possible formats, it is not possible without creating _validate_type_* functions.

[validictory](http://validictory.readthedocs.org/en/latest/usage.html#specifying-custom-types) allows this because it handles custom types in a way to the proposal in Issue [#96](https://github.com/nicolaiarocci/cerberus/issues/96)

**Comment by funkyfuture** [comment]
i think an example would be useful.

would that be an equivalent to the items-constraint in a list's context?

**Comment by CD3** [comment]
I'd like to be able to do something like this (or equivalent)

```
      schema   = { 'parts' : { 'type' : 'list'
                             , 'schema' :
                               { 'type' : [ 'dict', 'string' ]
                               , 'schema' :
                                 [
                                   { 'model number' : {'type' : 'string', 'required' : True}, 'count' : {'type' : 'integer'}  }
                                  ,{ 'serial number' : {'type' : 'string', 'required' : True}, 'count' : {'type' : 'integer'}   }
                                 ]
                               }
                            }
                 }
      v = Validator(schema)
      document = { 'parts' : [ 
                              { 'model number'  : 'MX-009', 'count' : 100 }
                             ,{ 'serial number' : '898-001', 'count' : 20 }
                             ,  'misc'
                             ]
                 }

      res = v.validate( document )

```

so 'parts' is allowed to be a string or a dict. If it is a dict, it either has to have a 'model number' entry or 'serial number' entry.

I don't think it items-constraint works here. My understanding is that the items-constraint makes sure that the items in a list (in the document) each validate to some schema.

**Comment by funkyfuture** [comment]
> would that be an equivalent to the items-constraint in a list's context?

i reviewed the documentation and found that also these constraints beside *schema* and *type* could be used with a set of rules that are evaluated as an or-condition:

- dependencies
- items
- propertyschema
- regex
- schema (dict)
- valueschema

therefore is suggest a more generic solution that allows or-evaluated constraints.

**Comment by CD3** [comment]
I agree, this would be useful.

Wouldn't there need to be another constraint added, for example 'anyof', to handle this transparently? You could store a list of or'able constraints, but then user defined validation functions would not have have access to them. What about allowing something like this:

```
 schema   = { 'parts' : { 'type' : 'list'
                             , 'schema' :
                               { 'type' : [ 'dict', 'string' ]
                               , 'schema' :
                                 {'anyof' : [
                                   { 'model number' : {'type' : 'string', 'required' : True}, 'count' : {'type' : 'integer'}  }
                                  ,{ 'serial number' : {'type' : 'string', 'required' : True}, 'count' : {'type' : 'integer'}   }
                                 ] }
                               }
                            }
                 }
```

**Comment by funkyfuture** [comment]
two further thoughts on that:

looks cool. but, wouldn't it be more generic this way:

```python
schema = {'parts': {'type': 'list',
                    'schema': {
                        'anyof': [
                            [{'type': 'dict'}, {'type': 'string'}],
                            [{'schema': {'model number': {'type': 'string', 'required': True}, 'count': {'type': 'integer'}}},
                             {'schema': {'serial number': {'type': 'string', 'required': True}, 'count': {'type': 'integer'}}}
                                 ]
                              }
                  }
         }
```

thus, the-`anyof`-rule is takes a *list of lists* where the inner lists' rules are or-evaluated while the outer list is and-evaluated for *any* schema. which also allows this:

```python
schema = {'foo_property': 'anyof': [[…]]
```

or to stick to the current `type`'s notation, evaluate a given list for any rule as a set of valid values. which eventually is an extension if the `allows`-constraint to more types. but that would break client code.

unfortuantely these approaches do not solve #96, but would be a good base to make subsets of rules not only dependent on `type`.

**Comment by CD3** [comment]
Well, I think that having the outer lists and'ed would not do what the name 'anyof' would suggest. Perhaps two new rules, `anyof` and `allof`. Then one function could be written to implement both that accepts a flag telling it if all item need to validate or just one.

I think #96 could be solved by adding support for in-lined types. If the entry in a type list is a dict, then it should just be treated as a schema that should be used for validation. This is how [validictory](http://validictory.readthedocs.org/en/latest/usage.html#specifying-custom-types) handles types.

**Comment by funkyfuture** [comment]
yeah, that't better readable. other names for these rules could be `all_schemas` and `any_schema` to be more clear.

i proposed the dict-notation for `type`, but eventually the library would be usable more flexible if you could  define for further rules for each `any`-rule that is considered true.

**Comment by CD3** [comment]
``all_*`` and ``any_*`` would be easier to implement. You could just check constraint names for the `all_` or `any_` prefix and add a loop over all items. then the non-prefixed versions would be a special case and you have everything use the prefixed version. So if `name` is encountered, just put its value in a list and call `any_name` instead.

However, would it allow mixing?
```
schema = { 'param' : { 'type' : 'dict'
                                    'any_schema' : [
                                            'all_schema' : [...],
                                            'all_schema' : [...]
                                    ]}}

```
which says I need one set of schema to validate, but all of the schemas in the set must validate.

**Comment by funkyfuture** [comment]
sounds too good, would be great if it'd become true. i encourage you to try this out. as your idea is a grammatical one, this would also allow blacklisting easily with a `not_`-prefix.

> then the non-prefixed versions would be a special case and you have everything use the prefixed version. So if name is encountered, just put its value in a list and call any_name instead.

i'm not sure if i get this part. i would do it the other way around. the current set of rules stay as they are. just add handlers in case there's a meaningful prefix.

**Comment by CD3** [comment]
OK, I'll look into it. Your right, I wouldn't' want to try to port all of the existing rules to `any_`/`all_` .
