### ISSUE TITLE
Request: Allow pyyaml to be used in unit tests

### ISSUE THREAD

**Issue by CD3** [nicolaiarocci/cerberus#115]
I use YAML to write the schema in my applications, which is one of the greatest features of cerberus in my mind. I can write a schema for a configuration file in plain-text and load it into a nested dict.

I think the documentation should list this as a feature, but I'd also like to be able to write unit tests in YAML, it is a much cleaner syntax than nested a nested `dict`.

**Comment by funkyfuture** [comment]
yep, should be put into a `requirements-dev.txt` to not introduce a dependency.

**Comment by nicolaiarocci** [comment]
While a nice thing to have, I don't think this is necessary. I recon pyyaml is a cool tool, but it would inevitably add complexity for wanna be contributors who don't use/know YAML/pyyaml. Also I would not want the test suite to become a mix of yaml-ed/not yaml-ed tests, depending on who contributed the code.

I agree that it would probably be nice to have a pyyaml/cerberus usage example in the docs, though.

**Comment by CD3** [comment]
All right, I'll work on the docs.
