### ISSUE TITLE
suggestion to make it easier to find this project

### ISSUE THREAD

**Issue by schettino72** [nicolaiarocci/cerberus#120]
Looks like `cerberus` is exactly what I was looking for. Bad news is that I was searching for `schema` and `validation` keywords on PyPI and didnt notice your package... By lucky, because you just did a release today, I noticed your project.

I would suggest you to add the word `schema` somewhere in the project description and/or keywords. So people can find your project! thanks

**Comment by aleksey-kutepov** [comment]
I'm strongly agree with that. I found cerberus during reading python-eve sources.
And switched to it from jsonschema library. Probably it worth to mention "light and powerful jsonschema alternative" as well in tags or somewhere else.

**Comment by nicolaiarocci** [comment]
Guys, while I did not follow up on you, I actually updated the project description a long while ago. I apologize for not getting back to you sooner. Thanks for your suggestions.
