### ISSUE TITLE
Required if another field is present

### ISSUE THREAD

**Issue by jmesquita** [nicolaiarocci/cerberus#121]
Is this supported by any chance? I am sorry, could not find a mailing list make this question so I posted it here.

**Comment by funkyfuture** [comment]
could you please elaborate your question? preferably with a use-case-example.

may it be possible that the new `oneof`- or `anyof`-rules may be of use?

**Comment by jmesquita** [comment]
Not sure, really. The use case would be:

If the type of product is cars, then color is required. If the type os bikes, it is not.

**Comment by funkyfuture** [comment]
```python
schema = {'oneof` = [{'product_type': {'regex': '^car$'}, 'color': {'required': True}},
                     {'product_type': {'regex': '^bike$'}}]}
```

if that helps, how can the documentation be improved regarding this?

**Comment by funkyfuture** [comment]
@nicolaiarocci i propose to close this issue since there hasn't been any feedback by @jmesquita for almost two weeks.

**Comment by jmesquita** [comment]
I am deeply sorry about this. I had a very close relative that has died and
haven’t had a chance to get to this. I will next week. I believe you can
close the issue and I will reopen in case this is still outstanding.

Again, I am sorry for not providing feedback.

On Mon, Jul 13, 2015 at 8:27 AM, Frank Sachsenheim <notifications@github.com

**Comment by funkyfuture** [comment]
my condolences.

thanks for your feedback. no need to close it then.
and sure, you can always reopen an issue.

**Comment by jmesquita** [comment]
Guys, sorry for the loong delay on this. I guess documentation is pretty complete, specially since we can use dependencies for that now. Closing the issue. Thank you for your patience.
