### ISSUE TITLE
Use cases

### ISSUE THREAD

**Issue by richiverse** [nicolaiarocci/cerberus#124]
Use Case 1 - record level validation:
Say I have 2 fields. "Amount" and "Calculation Type". Amount is always a float, however when calculation type is "Percent", Amount must be bounded from 0 to 100.

Use Case 2 - table level validation:
Say I have multiple records and after grouping certain fields, no duplication can be present.

Use case 3 - Multiple coercion functions:
I need to convert a value to string, and perform a couple of other functions before validation. Any tips here?

Appreciate your help! This is probably one of the coolest python projects I've seen in a while.

**Comment by manugarri** [comment]
+1

**Comment by funkyfuture** [comment]
1) http://docs.python-cerberus.org/en/latest/customize.html
2) i don't understand the scenario
3) #102

@manugarri, can you please elaborate?

**Comment by richiverse** [comment]
@funkyfuture 

For (2):
Say I had a column with 1000 rows and I want to say that all 1000 values in this column are in a table of 25000 rows, how would I do that in cerberus?

Or

How would I determine 1 or more columns in aggregate are unique?

**Comment by nicolaiarocci** [comment]
Cerberus is only meant to validate one row against a set of rules. Not really designed for such an use case (which seems more suited for a relational database)

**Comment by richiverse** [comment]
ok thx
