### ISSUE TITLE
Proposal: Allow dependent values to be bool, int, etc...

### ISSUE THREAD

**Issue by hbarroso** [nicolaiarocci/cerberus#129]
It seems that dependencies with allowed values only work if these values are of type String. I don't understand this restriction. It would be useful to allow allowed values to be boolean or int for example.

This validates as usual:
```python
schema = {'field1': {'required': False}, 'field2': {'required': True, 'dependencies': {'field1': 'one'}}}
document = {'field1': 'one', 'field2': 7}
```

This should return an error:
```python
schema = {'field1': {'required': False}, 'field2': {'required': True, 'dependencies': {'field1': True}}}
document = {'field1': False, 'field2': 7}
```
But still returns as valid.

Looking at the ```cerberus.py``` source code at the line 554 you see:
```python
if isinstance(context, _str_type) and context not in dep_values:  # noqa
   ...
```

By removing the ```isinstance(context, _str_type) an``` everything works. But again, I wonder why it's there in the first place.

Thanks,

**Comment by funkyfuture** [comment]
do the tests pass with this change?

**Comment by nicolaiarocci** [comment]
This was a recent regression, should be fixed now. Thanks!
PS: might be a nice idea to also add a test so we don't fall into it again in the future.
