### ISSUE TITLE
Proposal: Add `default`-normalization rule

### ISSUE THREAD

**Issue by funkyfuture** [nicolaiarocci/cerberus#131]
this is a follow-up of [this](https://github.com/nicolaiarocci/cerberus/issues/102#issuecomment-122241232).

A `default`-rule would substitute any `None`-values, empty Mapping and Sequence-instances and numbers equal to zero for a given field with the provided constraint's value while a document is normalized. if the field isn't present at all, it will be added to the document with the constraint's value.

the `default`-constraint should be processed after coercing.

example:

```python
>>> schema = {'amount': {'default': 1}}
>>> document = {'amount': None}
>>> v.validated(document, schema)
{'amount': 1}
>>> document = {'model': 'The Robots'}
>>> v.normalized(document, schema)
{'model': 'The Robots', 'amount': 1}
```

**Comment by nicolaiarocci** [comment]
Now that we also transform the incoming document, I guess that stuff like this is welcome. Actually, we implemented a `default` rule in Eve so I know it is useful :) :+1:

**Comment by funkyfuture** [comment]
Is there a difference of Eve's rule-design to my proposal?

**Comment by nicolaiarocci** [comment]
Yes. Of course Eve does not have or need `normalized` since input documents are stored to the backend (with defaults added as needed).
