### ISSUE TITLE
some advise about reserved schema config key

### ISSUE THREAD

**Issue by MacHu-GWU** [nicolaiarocci/cerberus#134]
Because some key name are reserved, such as "type", "schema", "max", ...
Why not using mongodb style commands? use "$type", "$schema", "$max", ...?

**Comment by nicolaiarocci** [comment]
You don't have reserved words for documents. `type`, `schema`, etc. are only needed for the validation schema. You can have a schema like this for example:

    >>> schema = {'schema': {'type': 'dict', 'schema': {'name': {'type': 'string'}}}}

And then you can do
    
    >>> document =  = {'schema': {'name': 'mike'}}
    >>> v = Validator(schema)
    >>> v.validate(document)
    True
