### ISSUE TITLE
coerce and nullable

### ISSUE THREAD

**Issue by kseniyam** [nicolaiarocci/cerberus#142]
The behaviour changed:

ID_SCHEME = {'_id' :{'type':'string', 'coerce':str, 'regex': r'[0-9abcdef]{24}', 'required':True, 'nullable':True}}
_id = {'_id':None}
v = Validator()
print(v.validate(_id, ID_SCHEME))
print(v.errors)

in version 9 this gives:
True
{}

and in version 10 the same gives:
False
{'_id': "value does not match regex '[0-9abcdef]{24}'"}

Is this intended change?

**Comment by funkyfuture** [comment]
i don't think any of both behaviours was intended.

nonetheless i'd consider the recent as 'correct'. you can either extend your regex and dismiss the `nullable`-rule or implement #102 for a more clever coercion.

**Comment by funkyfuture** [comment]
if you can omit the `coerce`-rule it should work as well. if i remember right, allowed `None`-values are not validated in-depth.
