### ISSUE TITLE
Booleans are accepted for type integer

### ISSUE THREAD

**Issue by mbalser** [nicolaiarocci/cerberus#144]
Internally cerberus 0.10 does the following:

    >>> isinstance(1, (int,))
    True
    >>> isinstance(True, (int,))
    True
    >>> isinstance(0, (int,))
    True
    >>> isinstance(False, (int,))
    True

Of course I could map True and False to integers using Value Coercion, but this seems awkward and feels it is not the correct thing to do when using a type check for integers and not explicitly for booleans.

**Comment by funkyfuture** [comment]
what you show is [Python's intended design](https://stackoverflow.com/questions/8169001/why-is-bool-a-subclass-of-int).

can you elaborate your use-case?

**Comment by funkyfuture** [comment]
btw, gh's markdown renders code between three backticks (not very accessible on qwertz-layouts).

**Comment by mbalser** [comment]
The usecase is a customer facing api where I use cerberus for input validation. I want to clearly distinguish between truth values (true/false) and integers (1....1024).

Of course you are right about the python design choice, but I would rather not like to expose python internal "way-of-doing-things" to a backend neutral api. So my suggestion is to keep the current way of handling bool/int for backwards compatibility and provide something like a "strict" parameter which enforces that int has to be a number and not a boolean.

**Comment by funkyfuture** [comment]
brainstorming for rule's name:
- `strict_boolean`
- `truth`
- `truth_value`
- `true_false`
- `True_False`
- `logical` (quiet broad term and already used in context for `*of`-rules)

**Comment by mbalser** [comment]
I think boolean is already strict - I guess only integer would require a "stricter" version - something like "integer_strict" or such.

The change itself should be quite trivial:

    def _validate_type_integer_strict(self, field, value):
        if not isinstance(value, _int_types) or isinstance(value, bool):
            self._error(field, errors.ERROR_BAD_TYPE.format("integer"))

**Comment by funkyfuture** [comment]
would the more generic `number` be suitable?

**Comment by mbalser** [comment]
Although "number" is very generic in regards to int/float, but I think it would be a good fit.

**Comment by funkyfuture** [comment]
yep, it isn't bound to a builtin-type anyway.

and numbers are infinite while 'true' / 'false' are (questionable,) very finite / determined concepts. ;-)

**Comment by arnauorriols** [comment]
I apologize for commenting on an already closed issue.

@mbalser https://github.com/nicolaiarocci/cerberus/issues/144#issuecomment-139282857 depicts precisely my opinion on this, and for me "number" is not suitable. Can you elaborate on the justification to expose Python's implementation details to a high-level tool like is Cerberus? 

(I sincerely hope `3 == 2 + True` was not really the Python's intended design, but rather an implementation trade-off)

**Comment by funkyfuture** [comment]
well, the types are not all high-level i think (e.g. `binary`, `datetime`).

meanwhile a release candidate has taken form; it would be possible to change that and break bw-compatibility. i think it's okay to be more strict as `{'type': 'integer'} ->  {'type': ('bool', 'integer')}` is an easy change.

> (I sincerely hope 3 == 2 + True was not really the Python's intended design, but rather an implementation trade-off)

if that is the case, it must be changed as other interpreters may implement it differently. someone must lookup the specs.

**Comment by cjauvin** [comment]
I'm new to Cerberus and recently stumbled upon this aspect of its design. I am validating some data structure decoded from a JSON string (in the context of a web API), and was surprised to find that a JS boolean, which gets mapped to a Python boolean by the JSON decoding, validates against a Cerberus `integer`. I agree with the "why expose a Python internal implementation aspect?" argument mentioned by others in this thread, and moreover, I would argue that Cerberus being an abstraction layer describing the data _above_ the level of the language being actually used (as is my case, where I go from JSON to Python), it makes even more sense to have a strict interpretation of what the types mean. If you already distinguish between an `integer` and a `number`, wouldn't it more coherent to also distinguish between an `integer` and a `boolean`?
