### ISSUE TITLE
Why not officially support blob, date data type? And provide a before, after criterion for datetime and date?

### ISSUE THREAD

**Issue by MacHu-GWU** [nicolaiarocci/cerberus#146]
Why not officially support blob, date data type? And provide a before, after criterion for datetime and date? I know it's easy with custom validator, but since it's easy, why not officially support them?

**Comment by funkyfuture** [comment]
what are you referring to as *blob*?

i can also think of other commonly encountered validations, like for networking and posix-stuff.

for such purposes, i think the best would be to add a module with contributed custom validators in dumb classes that can be used as mix-ins for custom validators:

```
class UserValidator(cerberus.Validator, cerberus.contrib.EMail):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)  # don't try this at home if Python < 3
        self.schema = {'name': {'type': 'string', 'regex': '[a-z]{3,12}'},
                       'email': {'type': 'email address'}}

# or set the schema in your business logic:

class UserValidator(cerberus.Validator, cerberus.contrib.EMail):
    pass
```

**Comment by funkyfuture** [comment]
concerning the before and after criteria: what about covering that by `min` and `max`? but that would be from / to criteria.

**Comment by funkyfuture** [comment]
can this issue be closed? any types can be used with `min` and `max` in the master branch.
