### ISSUE TITLE
reusable schema

### ISSUE THREAD

**Issue by justinbridou** [nicolaiarocci/cerberus#150]
Hi,
I went through the online doc to find out if cerberus supports any address schema concept but unfortunately I couldn't find anything related.  What I am after is a logic to reference a schema has a valid key value. Something like:
schema= {
  "address": { "type": "string"},
  "address_dict":{
     "type": "dict",
     "schema": {
        "address": { "$ref": "#/address" }
     }
}
Could you confirm if this is supported or not?
Thank you
Justin

**Comment by nicolaiarocci** [comment]
Hello, what would prevent you from doing:

````
address_schema = {'type': 'string'}

schema = {
    'address': address_schema,
    'address_dict': {
        'type': 'dict',
        'schema': {'address': address_schema}
    }

?

**Comment by justinbridou** [comment]
thank you for the quick reply. I works but when dumping the schema in a Json file format (for instance) it breaks all references hence the sharing of the address_schema definition. When I reload the saved schema I get
{u'address': {u'type': u'string'},
 u'address_dict': {u'schema': {u'address': {u'type': u'string'}},
  u'type': u'dict'}}
I am wondering whether the dependency keyword could do the trick?

**Comment by funkyfuture** [comment]
here are my thoughts how this might be solved:

1. a `DefinitionSchema` can be initialized with an optional `definitions`-argument (no, that's not the most unambigious idea for a name)
  1. that `definitions` is a *flat* mapping that holds sets of rules and their constraints per name which is a string
  2. these names can be used in `schema` to reference rules and their constraints
  3. on initialization:
    - the provided schema and definitions are stored as private properties
    - in `expand_definition_schema` the schema will be resolved accordingly
2. `Validator` fetches `definitions` from the currently used schema and uses them for child-validator's schemas
3. a protocol is designed to store a schema and definitions in one document
  - that document will be accessible as `DefinitionSchema.unresolved`-property (again, there is certainly a better name)
  - if necessary, encoders and decoders must be provided as well (`from_json` etc.)
4. a `Validator`-instance may have a `definitions`-property that it uses in conjunction with schemas passed to `validate`

would definitions that can refer other definitions desirable?

**Comment by justinbridou** [comment]
Hi,
Thks for coming back. 
I was actually looking for a single reference. A multiple level or even a tree of definition references would be more generic but not sure the benefit worth the implementation cost.

**Comment by funkyfuture** [comment]
i propose to close this issue in favor of a discussion in #215.
