### ISSUE TITLE
Any plans for GeoJSON types?

### ISSUE THREAD

**Issue by johnnywell** [nicolaiarocci/cerberus#154]
It would be nice if I could validate GeoJSON types, like those supported by MongoDB.
    
* Point
* LineString
* Polygon
* MultiPoint
* MultiLineString
* MultiPolygon
* GeometryCollection

**Comment by nicolaiarocci** [comment]
Hello, we actually have a Cerberus subclass implementing MongoDB GeoJSON validation in the Eve project. You could use [that code](https://github.com/nicolaiarocci/eve/blob/develop/eve/io/mongo/validation.py) as a reference and build your own GeoJSON enabled validator. 

Wether supporting these types in Cerberus proper or not, I am unsure. Looks like a very domain specific issue to me, but I could be wrong of course.

**Comment by johnnywell** [comment]
Wow thanks! 
It's pretty nice to see it already working, I really loved Eve when I first saw it and I discovered Cerberus through it, but I didn't noticed those types on Eve back then.

You are probably right about keeping it out of Cerberus since it intents are to validate schemes, not specific data types.

Anyway thanks again, I really appreciate what you've been doing.
