### ISSUE TITLE
Normalization not working for valueschema and propertyschema

### ISSUE THREAD

**Issue by dkellner** [nicolaiarocci/cerberus#155]
Hey there,

I just stumbled over the following issue: When using 'coerce' in valueschema or propertyschema, validator.document does not get updated accordingly. Consider the following (currently failing) tests:

```python

    def test_coerce_in_valueschema(self):
        schema = {'thing': {'type': 'dict',
                            'valueschema': {'coerce': int}}}
        v = Validator(schema)
        self.assertEqual(v.validated({'thing': {'amount': '2'}})
                                     ['thing']['amount'], 2)  # noqa

    def test_coerce_in_propertyschema(self):
        schema = {'thing': {'type': 'dict',
                            'propertyschema': {'coerce': int}}}
        v = Validator(schema)
        self.assertEqual(v.validated({'thing': {'5': 'foo'}})
                                     ['thing'][5], 'foo')  # noqa
```

I don't know whether this is actually meaningful in case of propertyschema. For valueschema, normalization should be possible IMO.

**Comment by funkyfuture** [comment]
that would work:

        schema = {'thing': {'type': 'dict',
                            'allow_unknown': {'coerce': int},
                            'schema': {}}}

but i see that it's not straightforward.

normalization of keys [can be achieved](http://docs.python-cerberus.org/en/latest/usage.html#renaming-of-fields) with a `'rename_handler': int`.

to streamline both, the need to give an empty `schema` would have to be removed.

**Comment by dkellner** [comment]
Thank you! This solves my problem for now :).
