### ISSUE TITLE
Coerce None to desired type?

### ISSUE THREAD

**Issue by proximous** [nicolaiarocci/cerberus#160]
Is there a way to coerce None into a float, string, int, etc?

It seems like None is handled special before coercion/validation?  I have tried:

    none_to_float = lambda v: float(0 if v is None else v)
    schema = {'my_float': {'type': 'float', 'coerce': none_to_float}}

But if I try: 

    my_doc = {'my_float': None}

I get an error that 'my_float' can't be None.  If I change the schema to:

    schema = {'my_float': {'type': 'float', 'nullable': True, 'coerce': none_to_float}}

Validation passes, but 'my_float' is still None (instead of the desired float(0)).

I have also tried a custom validator:

        class MyValidator(cerberus.Validator):
            def _validate_nonetofloat(self, nonetofloat, field, value):
                if value is None:
                    self.document[field] = float(0)

With the same results.

**Comment by funkyfuture** [comment]
by just reading the code, this seems like it should do as you expect:
https://github.com/nicolaiarocci/cerberus/blob/master/cerberus/cerberus.py#L342

if you have the capacities, feel free to debug.

**Comment by proximous** [comment]
Are you saying my approach should work and I should debug around Line 342?  I ask because my troubleshooting leads me to believe that a check for None seems to occur before Coerce is applied, so I either fail because I didn't allow None, or I allow None and Coerce is never called.

**Comment by funkyfuture** [comment]
yes, what you expect is a valid expectation and therefore the actual behaviour is wrong.

all validation is done after normalization (invoked from L425). your second example validates as expected (allowed None-values are not type-checked), but the normalization doesn't.

however, L342ff doesn't filter out `None`-values (and neither does it care about `nullable`-rules). thus, i i have no clue what's wroong there w/o debugging.

**Comment by proximous** [comment]
Patch 165 from @funkyfuture also fixes this issue. Many thanks!  Hopefully this patch can become part of an official release soon.

**Comment by nicolaiarocci** [comment]
#165 has been merged.

**Comment by proximous** [comment]
Awesome! Any plans for an official release with this soon?

**Comment by funkyfuture** [comment]
whoops, I wasn't aware that this is also solved. had no intentions.

It would be nice to have a test on this. But i'm locked out today after a gnome update.

**Comment by proximous** [comment]
I'm not familiar with writing test cases, but this was my simple test that fails with the stable version 0.9 and passes now with the current development version:

    none_to_float = lambda v: float(0 if v is None else v)
    my_schema = {'my_float': {'type': 'float', 'coerce': none_to_float}}
    my_doc = {'my_float': None}
    my_doc_coerced = {'my_float': 0.0}
    v = cerberus.Validator(my_schema)
    result = v.validated(my_doc)
    assert result['my_float'] == my_doc_coerced['my_float']
