### ISSUE TITLE
Coerce on List elements produces unexpect results

### ISSUE THREAD

**Issue by proximous** [nicolaiarocci/cerberus#161]
Slight modification of the example at: http://cerberus.readthedocs.org/en/latest/usage.html

    schema = {'a_list': {'type': 'list', 'schema': {'type': 'float', 'coerce': float}}}
    document = {'a_list': [3, 4, 5]}
    v.validated(document, schema)
    >>> {0: 3.0, 1: 4.0, 2: 5.0, 'a_list': [3, 4, 5]}

I would expect:

    >>> {'a_list': [3.0, 4.0, 5.0]}

Is this the intended behavior or a bug?

**Comment by funkyfuture** [comment]
it's a bug and is propably found here: https://github.com/nicolaiarocci/cerberus/blob/master/cerberus/cerberus.py#L359

**Comment by proximous** [comment]
Patch 165 from @funkyfuture fixes this issue.  Many thanks!
