### ISSUE TITLE
design question: should the regex-rule require a trailing $?

### ISSUE THREAD

**Issue by funkyfuture** [nicolaiarocci/cerberus#169]
usually i write very explicit regexes and was lost for a while when i did not as i stumbled across this:

``` python
self.assertFail({'foo': 'aBc'}, {'foo': {'regex': r'''[a-z]*$'''}}) # fails as expected
self.assertFail({'foo': 'aBc'}, {'foo': {'regex': r'''[a-z]*'''}}) # does not fail
```

i see two issues here:

- it is inconsistent as a `$` is needed, but a `^` is not
- the need for a `$` seems to be an extra obstacle anyway

so, the question is, should we implicitly add the `$` in the regex-testing method?

**Comment by nicolaiarocci** [comment]
> so, the question is, should we implicitly add the $ in the regex-testing method?

good question. probably yes.
