### ISSUE TITLE
Take control over Exceptions caught on coerce

### ISSUE THREAD

**Issue by yohanboniface** [nicolaiarocci/cerberus#171]
Hi,

I'd like to catch more than `(ValueError, TypeError)` when running the coerce of a field (actually, `peewee.DoesNotExist` in case of a foreign key). As I'd like to use the same `coerce` method for my db fields and my schema fields, it would be very useful to be able to decide which exceptions are caught.

For example just having a Validator.COERCE_EXCEPTIONS tuple that can be overridden when inheriting from Validator.

I can work on a PR, but I'd love feedback before (I may be totally missing an obvious solution or a better implementation).

Thanks :)

**Comment by funkyfuture** [comment]
not sure if i'm missing soemthing, but #102 seems to be the obvious solution, isn't it?
a PR with an implementation would be highly appreciated.

**Comment by yohanboniface** [comment]
> not sure if i'm missing soemthing, but #102 seems to be the obvious solution, isn't it?

Not ideal in my use case, given that this would need creating one new method per field I want to deal with (to catch the new error type), while I'd like just to define which errors are considerer coerce error so I can *reuse* my field coerce method.

Very simple example would look like:

```python
class ForeignKeyField(peewee.Field):

    def coerce(self, value):
        # do some stuff that is also used when I deal with my model without cerberus.
        if not_happy:
            raise peewee.DoesNotExit()
        return value

class MyValidator(cerberus.Validator):
    COERCE_EXCEPTIONS = (ValueError, TypeError, peewee.DoesNotExist)

schema = {'myforeignkey': {'coerce': ForeignKeyField.coerce}}
```

Makes sense?

**Comment by funkyfuture** [comment]
counterexample with no error-handling, just pointing out that you wouldn't need to implement a method per field:

```py
class MyValidator(cerberus.Validator):
    def _coerce_foreign_key(self, field, value):
        self.document[field] = f(value)


schema = {'field1': {'coerce': 'foreign_key'},
          'field2': {'coerce': 'foreign_key'}}
```

(raising errors doesn't fit into a validator that is designed to be non-blocking.)

**Comment by funkyfuture** [comment]
fyi, i have extended the reported error by the exception messages, one might also add the exception to the `info` property of the created error. also, all of `Exception`'s subclasses are caught now. 

not merged yet: d676ce4dd3a3d0fdad1e8047c2513d8eb5354738

**Comment by yohanboniface** [comment]
Good move, thanks! :)

**Comment by funkyfuture** [comment]
can this be closed?
