### ISSUE TITLE
Configure regex validation to be case insensitive

### ISSUE THREAD

**Issue by luizpericolo** [nicolaiarocci/cerberus#173]
I know it is not possible to express case insensitivity flag in the actual regex string in python, so I guess that cerberus could use another attribute to manage this, for instance: regex_case.

**Comment by funkyfuture** [comment]
you could fiddle around with the `anyof`-rule (or similar) and `lower`/`upper`-methods of strings. could you?

**Comment by luizpericolo** [comment]
This does not sound optimal since I'd have to have two versions of my regex, the lower and the upper case version, if I were to use anyof as you suggested. This is bad because If anything on the regex changes I have to change it on the other version aswell.

**Comment by luizpericolo** [comment]
I'm debugging the regex validation process and I realize that my suggestion might not be feasible.
Maybe you could add a ```regex_case``` attribute to the Validator constructor, but I don't know if that does really make sense, specially if you would like some regex to be case sensitive and others not.

I'd be willing to contribute to this, but I just can't think of a good solution for this problem.

**Comment by luizpericolo** [comment]
Maybe change the ```regex``` key mapping from ```str``` to ```dict``` would be a good solution.
Something along the lines of:

    data_format = {
        'name': {
            'type': 'string',
            'regex': {
                'pattern': r'^[a-z0-9]$', 
                'case': 'insensitive'
            }
        }
    }

The problem then would be how to maintain backwards compatibility to the current syntax of regex validation.

**Comment by funkyfuture** [comment]
maintaining backward compatibility wouldn't be a problem. (duck-typing per instance-tests, you'll find a lot of these in the code.)
however, i suggest to name the second parameter `flags` and let that be an integer like the parameter with the same name for `re.compile`.
