### ISSUE TITLE
Recursion issue when using a recursive schema

### ISSUE THREAD

**Issue by carlos-alberto** [nicolaiarocci/cerberus#176]
We are trying to upgrade to the master branch currently, however the functionality we were currently using to define a recursive schema appears to be broken on the latest release

0.8
===

    In [1]: from cerberus import Validator

    In [2]: schema = {'a': {'type': 'integer'}, 'b': {'keyschema': {'type': 'dict', 'schema': None}}}

    In [3]: schema['b']['keyschema']['schema'] = schema

    In [4]: data = {'a': 1, 'b': {'c': {'a': 10}, 'd': {'a': 10000}}}

    In [5]: validator = Validator(schema)

    In [6]: validator.validate(data)
    Out[6]: True

master
======

    In [1]: from cerberus import Validator

    In [2]: schema = {'a': {'type': 'integer'}, 'b': {'valueschema': {'type': 'dict', 'schema': None}}}

    In [3]: schema['b']['valueschema']['schema'] = schema

    In [4]: validator = Validator(schema)
    ...
    .virtualenvs/connect/lib/python3.4/site-packages/cerberus/cerberus.py in update_to_valueschema(constraints)
       1275                                          "Use 'valueschema' instead.")
       1276         for key, value in constraints.items():
    -> 1277             constraints[key] = update_to_valueschema(value)
       1278         return constraints
       1279

    .virtualenvs/connect/lib/python3.4/site-packages/cerberus/cerberus.py in update_to_valueschema(constraints)
       1275                                          "Use 'valueschema' instead.")
       1276         for key, value in constraints.items():
    -> 1277             constraints[key] = update_to_valueschema(value)
       1278         return constraints
       1279

    .virtualenvs/connect/lib/python3.4/site-packages/cerberus/cerberus.py in update_to_valueschema(constraints)
       1275                                          "Use 'valueschema' instead.")
       1276         for key, value in constraints.items():
    -> 1277             constraints[key] = update_to_valueschema(value)
       1278         return constraints
       1279

    .virtualenvs/connect/lib/python3.4/site-packages/cerberus/cerberus.py in update_to_valueschema(constraints)
       1275                                          "Use 'valueschema' instead.")
       1276         for key, value in constraints.items():
    -> 1277             constraints[key] = update_to_valueschema(value)
       1278         return constraints
       1279

    .virtualenvs/connect/lib/python3.4/site-packages/cerberus/cerberus.py in update_to_valueschema(constraints)
       1267     # TODO remove on next major release
       1268     def update_to_valueschema(constraints):
    -> 1269         if not isinstance(constraints, Mapping):
       1270             return constraints
       1271         if 'keyschema' in constraints:

    .virtualenvs/connect/lib/python3.4/abc.py in __instancecheck__(cls, instance)
        186             if (cls._abc_negative_cache_version ==
        187                 ABCMeta._abc_invalidation_counter and
    --> 188                 subclass in cls._abc_negative_cache):
        189                 return False
        190             # Fall back to the subclass check.

    .virtualenvs/connect/lib/python3.4/_weakrefset.py in __contains__(self, item)
         73         except TypeError:
         74             return False
    ---> 75         return wr in self.data
         76
         77     def __reduce__(self):

Is this a known issue? Are recursive schemas something Cerberus intends to support?

**Comment by nicolaiarocci** [comment]
Good catch, this also happens with 0.9.x. You could workaround with: 

`schema['b']['keyschema']['schema'] = copy.deepcopy(schema)`

**Comment by carlos-alberto** [comment]
Cheers. I think that would only allow 1 level of recursion, we want arbitrary nesting. Is this possible?

**Comment by nicolaiarocci** [comment]
Well problem is, your schema is going to hit python recursion limit when inspected and, since we're now using recursion to scan the schema, it is hard to get around it. You could use [`sys.setrecursionlimit()`](https://docs.python.org/2/library/sys.html#sys.setrecursionlimit) to raise the recursion limit, but in your case I don't think that would help.

I was looking at [pickle documentation](http://docs.python.org/library/pickle.html#what-can-be-pickled-and-unpickled), where they have this note indeed:

> Trying to pickle a highly recursive data structure may exceed the maximum recursion depth, a RuntimeError will be raised in this case. You can carefully raise this limit with `sys.setrecursionlimit()`.

Given the limited impact of this issue, I don't think we want to replace the current algorithm with an alternative to recursion, also because it is being used in several places around the codebase so it would not make sense to only address it here.

**Comment by funkyfuture** [comment]
i think that should be solved when approaching #150.

two things changed since 0.8 that have an impact on a recursive schema, if i remember correctly:
- subschemas are validated (recursion isn't checked)
- schemas are wrapped into a `DefinitionSchema`

**Comment by carlos-alberto** [comment]
Just to check back in on this, we decided to go with 10 levels of nesting which should be enough for our usage.

**Comment by funkyfuture** [comment]
@carlos-alberto can you provide a simple test for this? i guess i could fix it, if the recursion is at the first level of the schema.

**Comment by carlos-alberto** [comment]
You can see a test in this commit on my fork https://github.com/carlos-alberto/cerberus/commit/2a719014baebc634940cc752262cb163e0707831
