### ISSUE TITLE
False positives using dependencies with value restrictions

### ISSUE THREAD

**Issue by adityaramesh** [nicolaiarocci/cerberus#181]
The following example validates under Cerberus 0.9.2, but based on my reading of the documentation, I would not expect it to. Is this a bug?

    schema = {'foo': {'required': False}, 'bar': {'required': True, 'dependencies': {'foo': 'one'}}}
    v = Validator(schema)
    document = {'foo': 0, 'bar': 0}
    v.validate(document) # Outputs 'True'

Value restrictions for integer-valued fields also seem to have no effect:

    schema = {'foo': {'type': 'integer', 'required': False}, 'bar': {'required': True, 'dependencies': {'foo': 0}}}
    v = Validator(schema)
    document = {'foo': 1, 'bar': 0}
    v.validate(document) # Outputs 'True'

**Comment by funkyfuture** [comment]
with the current master i can't reproduce this behavior, this test is passing:

```python
    def test_issue_181(self):
        schema = {'foo': {'required': False},
                  'bar': {'required': True, 'dependencies': {'foo': 'one'}}}
        document = {'foo': 0, 'bar': 0}
        self.assertFail(document, schema)

        schema = {'foo': {'type': 'integer', 'required': False},
                  'bar': {'required': True, 'dependencies': {'foo': 0}}}
        document = {'foo': 1, 'bar': 0}
        self.assertFail(document, schema)
```

**Comment by adityaramesh** [comment]
Awesome, so I guess this will be fixed in the next release. I'll reopen if this is not the case.
