### ISSUE TITLE
required only on update

### ISSUE THREAD

**Issue by yohanboniface** [nicolaiarocci/cerberus#183]
I've a usecase where I want a field ("version") to be required only on update. In short, people updating a resource should define which version they are creating. On resource creating, this should not be needed.

This does not seems to be doable easily, so I will hack around on my end. But I open this issue for the record, as this seems to me a valid (though rare) use case.

**Comment by nicolaiarocci** [comment]
This looks more like a Eve related issue? Have you checked into bulti-in [Document Versioning](http://python-eve.org/features.html#document-versioning)?

**Comment by yohanboniface** [comment]
Nope, I'm using cerberus in falcon based project: https://github.com/etalab/ban :)
But thanks for the pointer, I'll have a look at Eve to see how it's done there :)

**Comment by funkyfuture** [comment]
is this still an issue?
