### ISSUE TITLE
0.9.2 on pypi seems to not match 0.9.2 on github

### ISSUE THREAD

**Issue by cricklet** [nicolaiarocci/cerberus#184]
`test_coerce_in_subschema` is [a test](https://github.com/nicolaiarocci/cerberus/blob/189122fb5d2d699d8d73eca2a063f2ee8b08eaf5/cerberus/tests/tests.py#L1262) that exists on GitHub for the commit 189122fb5d2d699d8d73eca2a063f2ee8b08eaf5, which is the release commit for 0.9.2.

However, when I install cerberus (0.9.2) via `pip`, I can't find `test_coerce_in_subschema` in `tests/`.

![screen shot 2015-12-21 at 5 42 19 pm](https://cloud.githubusercontent.com/assets/659021/11945966/4419967c-a80a-11e5-807a-f43b2c009c31.png)

**Comment by nicolaiarocci** [comment]
Thanks for reporting. Honestly, I am not quite sure about what happened there. I will have to review my tagging/merging/release routine. Since it's back with 0.10 I am closing this ticket.
