### ISSUE TITLE
Proposal: support all builtin types

### ISSUE THREAD

**Issue by funkyfuture** [nicolaiarocci/cerberus#186]
as of now the following of Python's builtin data types are not covered with test methods:
bytes, bytearray, callable, complex, frozenset, tuple

as base for a variety of validatiors cerberus could be hold responsible when becoming final to cover all of Pythons' basic types.
further types could come from stdlib's `collections.abc` and `inspect`.

however this can also be delegated to a library resembling extensions to cerberus.

**Comment by nicolaiarocci** [comment]
> as base for a variety of validatiors cerberus could be hold responsible when becoming final to cover all of Pythons' basic types.

Looks good to me.

> further types could come from stdlib's collections.abc and inspect. however this can also be delegated to a library resembling extensions to cerberus.

I would keep these out.

**Comment by funkyfuture** [comment]
the problem with my proposal is that the types `list` and `dict` aren't actually covered as these types check for `Sequence` and `Mapping`. which is fine, but having more non-abstract container types would  somewhat establish an inconsistency. 
so, i think it may be better to leave it as it is and rather provide a pure `PythonTypesValidator`.

**Comment by nicolaiarocci** [comment]
ok closing for now
