### ISSUE TITLE
Refactor DefinitionSchema.validate

### ISSUE THREAD

**Issue by funkyfuture** [nicolaiarocci/cerberus#189]
imo this code is quiet a mess. in terms of readability and consistence and thus maintainability i found
it rather horrific. maybe there's a validation tool to get this straight?

as some rules validations popped up to be missing every now and then, a schema-based validation seems to be a promising approach to reduce possible lack of validation.
maybe a validation of a rule could be retrieved from its method's docstring.

**Comment by nicolaiarocci** [comment]
I think it's fine for the time being.

**Comment by nicolaiarocci** [comment]
Well I see you went ahead anyway. I admit I like what you did.

**Comment by funkyfuture** [comment]
when you closed the ticket i already was working into that direction. and it turned out to be a good motor to hit some goals i wasn't aware they existed.
i'm especially fond of the coupling of (custom) rules and their validation constraints.
next i will look into, is to also normalize / expand the schema with cerberus itself. but there's still some unidentifed nut to crack. if i succeed, i hope it solves #168 with it as well.
