### ISSUE TITLE
Proposal: Rename 'propertyschema' to 'keyschema'

### ISSUE THREAD

**Issue by funkyfuture** [nicolaiarocci/cerberus#191]
i pledge to rename the 'propertyschema' rule to 'keyschema'. there are records concerning this naming (#83).
it would be great to have that pythonicly consistent with a 1.0 release.

**Comment by nicolaiarocci** [comment]
:+1:

**Comment by funkyfuture** [comment]
i think this can't be included in a `0.10` as it would break old schemas (with `keyschema` instead of `valueschema`).

**Comment by nicolaiarocci** [comment]
I don't want to leave something that breaks backward compatibility behind as, ideally, 1.0 API is going to be around for a very long time. Either we renounce to this, or we bite the bullet and include with 1.0.

**Comment by funkyfuture** [comment]
but my question was regarding a `0.10` release as which this issue is labelled.

do you plan a `0.10` before a `1.0` release? i'm asking especially due to #187. if there was a `0.10` i would seek an intermediate solution.

**Comment by nicolaiarocci** [comment]
AH sorry for the confusion. I don't plan a 0.10. Next one will be 1.0
