### ISSUE TITLE
Comparison across differnet fields of a dict

### ISSUE THREAD

**Issue by vanga** [nicolaiarocci/cerberus#197]
I am not sure if this is currently possible, I have looked at the documentation and couldn't find an appropriate schema rule

if I have doc like  `doc = {"a":1,"b":2,"c":1}`
I need to check `if doc["a"] == doc["b"]`

Thanks.

**Comment by funkyfuture** [comment]
i suggest using a [custom validator](http://docs.python-cerberus.org/en/latest/customize.html).

**Comment by vanga** [comment]
@funkyfuture Thanks,Will try that.
