### ISSUE TITLE
combination of minlength and empty

### ISSUE THREAD

**Issue by stijnvanhoey** [nicolaiarocci/cerberus#205]
Consider the following example, combining the rules `empty` and `minlength`:

```python
schema = {'role': {'type': 'string', 'minlength':3, 'empty':True}}
v = Validator(schema)
v.validate({'role': ''})
v.errors
```
which gives `{'role': 'min length is 3'}`. Empty is ok (as done with empty), but minlength provides an error, this is as expected. 
However, I'm aiming for the specific case where I want to have either length > 3 OR an empty string as valid options. Combination of this can be done with the anyof (a two-char should provide an error):

```python
schema = {'role': {'anyof': [{'minlength':10}, {'empty':True}]}}
v = Validator(schema)
v.validate({'role': 'te'})
```
which provides `True`? Is this intentionally? And with what kind of design purpose?

Still, a workaround is using the following:
```python
schema = {'role': {'anyof': [{'minlength':10}, {'maxlength':1}]}}`
```
but I would expect that `'maxlength':1` is actually just a verbose version of `'empty':True`? What is actually the aimed usage for empty=True?

**Comment by funkyfuture** [comment]
which version are you using?

**Comment by funkyfuture** [comment]
`empty` with `True` (which is the default)  doesn't fail with non-empty values. you only need to declare it with `False` if an empty value shall fail the validation.

http://docs.python-cerberus.org/en/latest/validation-rules.html#empty

please submit improvements to the documentation is you have any proposals.

**Comment by zDawG** [comment]
I solved in by using something like the following though it's not the most intuitive:
`
'tags': {
    'type': 'list',
    'allowed': ['abc', 'def', 'ghi'],
    'minlength': 3,
    'maxlength': 3
}`
