### ISSUE TITLE
Why error value can be string and list of strings?

### ISSUE THREAD

**Issue by andreymal** [nicolaiarocci/cerberus#210]
It is uncomfortable for me. I have to write extra type checking.

This is OK (except #209, but it is not about that):
```python
>>> v = Validator({'name': {'type': 'string', 'minlength': 6, 'regex': '[A-z]+'}})
>>> v.validate({'name': '©'})
False
>>> for field, value in v.errors.items():
...  print(field)
...  for error in value:
...   print(' -', error)
... 
name
 - max length is 6
 - value does not match regex '[A-z]+'
```

But:
```python
>>> v.validate({'name': 'abc'})
False
>>> for field, value in v.errors.items():
...  print(field)
...  for error in value:
...   print(' -', error)
... 
name
 - m
 - a
 - x
 -  
 - l
 - e
 - n
 - g
 - t
 - h
 -  
 - i
 - s
 -  
 - 6
```

WAT

I don't wish write `if isinstance(value, str)`!

**Comment by nicolaiarocci** [comment]
This happens on the master branch, right? Should not be on stable (v0.9.2).

**Comment by funkyfuture** [comment]
nah, that's the behaviour how errors are stored in `Validator.errors` also before `0.10`. but it's also implemented in the `BasicErrorHandler` for backward compatibility.

@andreymal there's also a lower-level access to errros in the master branch: http://docs.python-cerberus.org/en/latest/errors.html

**Comment by andreymal** [comment]
Lower-level access is too low :)

>for backward compatibility.

I only can deal with it and write a custom errorhandler?

**Comment by funkyfuture** [comment]
with a new major relase coming, this behavior could be changed. there shouldn't be an impact on client code unless it could handle single errors on a field anyway.

**Comment by nicolaiarocci** [comment]
👍
