### ISSUE TITLE
Proposal: completely switch to py.test

### ISSUE THREAD

**Issue by funkyfuture** [nicolaiarocci/cerberus#213]
this tools has been released recently: https://github.com/dropbox/unittest2pytest

if it does its job good, it shouldn't be such an effort to rewrite all tests as they are usable with `pytest`.

i'd be much in favor for it, alone for the heavily reduced char count of the `tests.py`. but certainly after an 1.0 release.

**Comment by nicolaiarocci** [comment]
Interesting.

**Comment by funkyfuture** [comment]
just two cents:

- used it. it's realiable. it's not without straight forward effort anyway. but a good start.
- pytest doesn't run on pyston yet.

**Comment by nicolaiarocci** [comment]
Partially addressed by #259
