### ISSUE TITLE
Design discussion about reusable and recursive schemas

### ISSUE THREAD

**Issue by funkyfuture** [nicolaiarocci/cerberus#215]
In the past several issues have been brought up that relate to reusable schema definitions and recursive schemas.

## Recursive schemas

Before the function `expand_definition_schema` was introduced to normalize a schema in all its levels it was easy to define a recursive schema (e.g. #176):

```python
schema = {'field': {'type': 'dict'}}
schema['field']['schema'] = schema

```

Also, schemas were only validated on the first level of fields and their rules, but further defintions for rules like `schema` went mostly unvalidated.

But since that function and the deeper-level validation were added, any recursion will lead to an infinite recursion while schema validation. This is an implementation flaw, because it's redundant processing anyway.

A possible solution to this would be to keep track of expanded / validated schemas and ignore them on further encounters while expanding and validating.

To serialize such schema is just not possible.

## Reusable schemas

Similarly it's easy to reuse a schema defintion in multiple parts of a schema:

```python
user_schema = {'uid': {'type': 'integer', 'min': 1000, 'max': 0xffff}}
schema = {'sender': {'schema': user_schema},
          'receiver': {'schema': user_schema}}
```

This is well readable Python code, but when it comes to de-/serialization of a schema like this there are drawbacks:

- the reused schemas are fully expanded by serialization leading to a possible vast amount of redundant data
- the reused schemas become anonymous and can't be manipulated at once by simply  updating one object

## Schema references to the rescue

Both problems can be tackled with referenced schemas, approximately with something like this:
 
```python
cerberus.register_schema('user_schema', {'uid': {'type': 'integer', 'min': 1000, 'max': 0xffff}})
schema = {'sender': {'schema': 'user_schema'},
          'receiver': {'schema': 'user_schema'}}
```

So, when the schema-rule is given a string, the validator would look up the corresponding schema defintion that has been registered before. Also, given a sequence of strings and mappings could be merged into one mapping.

To ensure the schemas' validity, cerberus must provide mechanics to validate schema references upon registration and when triggered by the user.

When this approach is chosen, there are some open design questions, at least these:

1. Would such schema registry be located on a module-, class- or instance-level? Or can any of these have one with a
   lookup from instance to module?
2. Would further namespacing be useful?
3. What's a good name? Registry? Schema storage? Schema definitions?
4. When would the existence of referenced schemas be checked? Upon schema validation or when initializing a document
   validation?
5. The very same is thinkable for rules sets defintions of fields. Should this also be given a shot while at it?

I think this should be solved before a 1.0 release because it enables much leverage how to structure the schemas of a project.

----
cc @carlos-alberto @justinbridou

**Comment by nicolaiarocci** [comment]
Overall I think this is a good idea, and I see the obvious advantages, but I fear the "over-engineering" factor. All of these features are already achievable with what we have now. With this being said

1 and 2. Since both approaches are valid, I kind of like the concept of keeping such a register out of the main Cerberus class. It might then be passed to the instance when/if needed. 
3. I like the `register_schema`/`schema_registry` pair.
4. It would be probably be nice to check them along with main schema validation.
5. I am actually already doing something like that right now. For example I define a `required_string` dict,  then reuse it anywhere it is needed. 

Would be good to gather  more feedback, especially from people using Cerberus in the wild.

**Comment by funkyfuture** [comment]
i must admit i'm a little irritated about the lack of feedback in the light of previous requests.

i will propably submit an implementation proposal after the weekend unless it gets too complex. one issue will certainly be the ambiguity of `schema` as in #226.

**Comment by nicolaiarocci** [comment]
I would say that we can close this now, as #228 added this feature.
