### ISSUE TITLE
is transparent_schema_rules still necessary?

### ISSUE THREAD

**Issue by funkyfuture** [nicolaiarocci/cerberus#218]
this option goes back to times when schemas were not validated against a schema tailored schemas for any extended validator.

i see no use in this option anymore unless one wants to enable people to use bad pactices (not validating a validation schema and properly define their rules) and thus i pledge to remove this option with the 1.0 release.

**Comment by funkyfuture** [comment]
no, this option seems obsolete: https://github.com/nicolaiarocci/cerberus/issues/217#issuecomment-199250297

**Comment by nicolaiarocci** [comment]
Sorry for not getting back to you lately, have been terribly busy. Agree that this is now obsolete.
