### ISSUE TITLE
Property Schema Now Causing Warning

### ISSUE THREAD

**Issue by seglberg** [nicolaiarocci/cerberus#222]
This is probably more of a question, than an issue. However, did the correct way to use `propertyschema` change recently on master (aka upcoming 0.10/1.0)? I now get a UserWarning, see below:

```python
schema = {
    "users": {
            "type": "dict",
            "required": True,
            "propertyschema": {
                "type": "string"
            }
      }
}

v = Validator(schema)
v.validate({"users": {"test_user": "user_information"}})

cerberus/cerberus.py:594: UserWarning: Normalizing keys of users: test_user already exists, its value is replaced.
```

Not sure if this is an issue or if there is a change in behavior that I need to adopt.

**Comment by funkyfuture** [comment]
nope, i'd say it's an issue. unfortunately i can't look into it this week.

but my guess is, that before [this iteration](https://github.com/nicolaiarocci/cerberus/blob/master/cerberus/cerberus.py#L589) all items in `result` where key and value are identical should be dropped.

**Comment by seglberg** [comment]
Had some free time this morning, decided to give it a go. See #224.
