### ISSUE TITLE
How do I check if an item is of the `bytes` type? Also, how do I test things are an instance of `tuple`?

### ISSUE THREAD

**Issue by fake-name** [nicolaiarocci/cerberus#223]
I'm on python 3, and I need to validate that certain objects are of `bytes` or `bytearray` type. 

I've tried all of the relevant type-names, and none of them appear to work. Additionally, there is apparently nothing in the documentation about either type.

**Comment by fake-name** [comment]
I also need to be able to test that an item is a `tuple`.

**Comment by funkyfuture** [comment]
the master-branch contains the `binary`-type: https://github.com/nicolaiarocci/cerberus/commit/4a23a192805204d4fc28d3f3ab98ae0677ed4ff1

the type `list` actually tests for any sequence type. due to that rather generic design the idea to add a `tuple`-type was dismissed. adding this type with a custom validator is easy.

**Comment by fake-name** [comment]
> the type list actually tests for any sequence type. due to that rather generic design the idea to add a tuple-type was dismissed. adding this type with a custom validator is easy.

Can... can you actually mention that in the docs? The word `tuple` does not exist on the page: http://docs.python-cerberus.org/en/stable/usage.html

**Comment by fake-name** [comment]
Oh, also, when will the master branch make it to PyPi? I wouldn't consider this actually fixed until the fix is actually *released*.

**Comment by funkyfuture** [comment]
no, the word `tuple` isn't mentioned, and there can be no exhausting list that covers all types that are sequences. that is why the doc concerning the abstract class is linked.

the master-branch won't make it to the PyPI, but the next release. this will be a `1.0`-release and isn't finished yet.

**Comment by funkyfuture** [comment]
btw, the docs from the master branch are reflected here: http://docs.python-cerberus.org/en/latest/usage.html

**Comment by fake-name** [comment]
> no, the word tuple isn't mentioned, and there can be no exhausting list that covers all types that are sequences. that is why the doc concerning the abstract class is linked.

Ok, I don't disagree with that, but you should at least cover the native included types. There's a grand total of maybe 10 types in majorly common use.
