### ISSUE TITLE
Usage of coerce inside a oneof statement not validated

### ISSUE THREAD

**Issue by stijnvanhoey** [nicolaiarocci/cerberus#230]
Using cerberus 0.10, the usage of a coerce statement inside a `oneof` environment seems to be ignored. 

When performing the following test, I would expect that the following validation would not invoke any errors, since the string '4' would first be tackled by the coerce:

```python
v = Validator({'code': {'oneof': [{'allowed': ['ab']},
                                  {'coerce': float,
                                   'type': 'float',
                                   'min': 3.0}]}})
v.validate({'code' : '4.'})
```

However, the following error is logged:
```python
{'code': [{'oneof': 'none or more than one rule validate'}, 'unallowed value 4', 'must be of float type'], 'definition 1': {'code': 'must be of float type'}, 'definition 0': {'code': 'unallowed value 4'}}
```
providing the error 'must be of float type' instead of testing the minimal value.

The statements: `v.validate({'code' : 4})` or `v.validate({'code' : 'ab'})` are accepted, as expected.

Should this be regarded as a bug or is this behavior intended in the implementation?

**Comment by funkyfuture** [comment]
it's intended. how would several normalization rules be handled in an *of-rule?

so, the bug is rather that you aren't told when the schema is validated.

**Comment by stijnvanhoey** [comment]
Indeed, I do understand that in an *of-rule environment there would be no information on how to normalize the document. With oneof you could use the single normalization that passes, but with allof or anyof, you would run into troubles...

Apparently, in version 0.9.2 the above validation did pass and the coerce worked within the *of environment. If this behavior is intended, then I can close this here, since it is solved.
