### ISSUE TITLE
question: validate a list

### ISSUE THREAD

**Issue by alcohol** [nicolaiarocci/cerberus#232]
Maybe I'm just approaching this all wrong, but I was wondering if the following is possible:

``` python
item = {
    'appid': {'type': 'integer', 'min': 1, 'required': True},
    'rank': {'type': 'integer', 'min': 1, 'required': True},
    'weight': {'type': 'float', 'required': True},
}

schema = {
    'type': 'list',
    'minlength': 1,
    'required': True,
    'schema': {
        'type': 'dict', 'schema': item
    }
}
```

I want to use the above to assert that a list I have, contains at least one element, and that each element of the list adheres to the item schema.

However, the above does not work since schema can only be applied to a dict.

So, as I understand it, I would have to wrap my list in a dict (e.g. `{'list': list}`), and then change my `schema` definition to:

``` python
schema = {
    'list': {
        'type': 'list',
        'minlength': 1,
        'required': True,
        'schema': {
            'type': 'dict', 'schema': item
        }
    }
}
```

I would really like to avoid this redundant nesting though but still use cerberus for the list validation, not "plain native" python (e.g. `if isinstance(list, collections.Iterable) and len(list) > 0:`).

**Comment by funkyfuture** [comment]
have you looked at http://docs.python-cerberus.org/en/stable/usage.html#schema-list ?

**Comment by alcohol** [comment]
Yes.. it's what I am using. But my question is not quite about that. Did I phrase it wrong?

**Comment by nicoCalvo** [comment]
I'm facing the same issue and I can't understand it from the docs. Could you  provide an example on how  validate a list of schemas? Thank you

**Comment by funkyfuture** [comment]
@nicoCalvo have you checked whether your question is covered somewhere on [StackOverflow](https://stackoverflow.com/questions/tagged/cerberus)?

**Comment by nicoCalvo** [comment]
I read more carefully the documentation and could understand it. Now it's working flawless. Thank you!

**Comment by dynnamitt** [comment]
Did you end up with wrapping in object or not?

      doc_ = dict(wrapper=doc) if isinstance(doc, list) else doc
