### ISSUE TITLE
Min, Max validation rule for string fields

### ISSUE THREAD

**Issue by vanga** [nicolaiarocci/cerberus#233]
Hello,

I am validating a document which has string fields with min max rules
doc = {"a": "1000"}
schema = {"a":{"min":1,"max":100}}

validating this doc always returns `True`
shouldn't this error out if the value is a string? (when min,max rules are being applied).
or may be convert the value to integer and then apply the rule? (may not be desired always I guess)

Thanks.

**Comment by funkyfuture** [comment]
you can compare strings and integers in Python, see:

- http://docs.python-cerberus.org/en/latest/validation-rules.html#min-max
- http://docs.python-cerberus.org/en/latest/validation-rules.html#type
- http://docs.python-cerberus.org/en/latest/normalization-rules.html#value-coercion

**Comment by vanga** [comment]
Thanks @funkyfuture .
`coerce` is what I needed, Thanks.
