### ISSUE TITLE
dependencies cannot be used inside of oneof ?

### ISSUE THREAD

**Issue by philwhln** [nicolaiarocci/cerberus#241]
Using cerberus version 1.0rc

I'm trying to structure this, so that if `a` is `1` then `b` is required, else if `a` is `2` then `c` is required. Is there something wrong with my usage here, or is this a bug?

```
>>> schema = {
...     "a": {
...         "type": "integer",
...         "oneof": [
...             {
...                 "allowed": [
...                     1
...                 ],
...                 "dependencies": [
...                     "b"
...                 ]
...             },
...             {
...                 "allowed": [
...                     2
...                 ],
...                 "dependencies": [
...                     "c"
...                 ]
...             }
...         ]
...     },
...     "b": {
...         "type": "string"
...     },
...     "c": {
...         "type": "string"
...     }
... }
>>> v.validate({"a": 1, "b": "123"}, schema)
False
>>> v.errors
{'definition 1': [{'a': ['unallowed value 1', "field 'c' is required"]}], 'a': [{'oneof': ['none or more than one rule validate']}, "field 'b' is required", 'unallowed value 1', "field 'c' is required"], 'definition 0': [{'a': ["field 'b' is required"]}]}
>>> v.validate({"a": 2, "c": "123"}, schema)
False
>>> v.errors
{'definition 1': [{'a': ["field 'c' is required"]}], 'a': [{'oneof': ['none or more than one rule validate']}, 'unallowed value 2', "field 'b' is required", "field 'c' is required"], 'definition 0': [{'a': ['unallowed value 2', "field 'b' is required"]}]}
```

**Comment by funkyfuture** [comment]
thanks for reporting. did you test if `dependencies` do work as expected outside a `oneof` clause?

and most certainly the errors representation concerning of-rules has to be revised.

**Comment by philwhln** [comment]
@funkyfuture I haven't yet hit an issue with `dependencies` outside of this, but only been using this module a few days :)

**Comment by funkyfuture** [comment]
fyi, i will not be able to look into this before this month will be passed. patch reviews are possible.

**Comment by nicolaiarocci** [comment]
@funkyfuture it's ok. Once this is sorted I plan on finally releasing 1.0 ([announcement](http://nicolaiarocci.com/cerberus-1-0-coming-going-awesome/) post)

**Comment by nicolaiarocci** [comment]
This SO question might be hitting the same issue: http://stackoverflow.com/questions/38084005/cerberus-schema-validation-dependency-depending-of-self-value/38168509#38168509

**Comment by gwainer** [comment]
I faced this problem in a similar case, Trying to solve the SO above mentioned by @nicolaiarocci , I tried to create a schema with two `bool` values, where only one of them must be `True` at a time.

To isolate, I tried a simpler example with the dependencies rule outside `one-of` rule, with a simple condition, but got no luck. 

For the example below, we have a schema with two `bool` values, `day_off` and  `absence`. `day_off` is allowed to be `True` only, and it depends from `absence` value being `False`.

    >> from cerberus.cerberus import Validator
    >>> to_bool = lambda v: v if type(v) is bool else str(v).lower() in ['true', '1']
    >>> 
    >>> schema = {
    ...     'day_off': {
    ...         'type': 'boolean',
    ...         'coerce': to_bool,
    ...         'allowed': [True],
    ...         'dependencies': {'absence': False},
    ...     },
    ...     'absence': {
    ...         'type': 'boolean',
    ...         'coerce': to_bool,
    ...     },
    ... }
    >>> v = Validator()
    >>> v.validate({'day_off': True, 'absence': True}, schema)
    True
    >>> v.errors
    {}

I expected that with this schema, a document with values `day_off: True` and `absence: True`, should not be validated. Only `day_off: True`, `absence: False` should be allowed, or something is wrong in my example.

**Comment by Abhisek1994Roy** [comment]
Was this fixed? Just asking. Need it for a project.
