### ISSUE TITLE
latest API doc is incomplete

### ISSUE THREAD

**Issue by funkyfuture** [nicolaiarocci/cerberus#246]
Used Cerberus version / latest commit: a7492107606500c5c2b14cc3cfba6d3c45592425

- I consulted these documentations:
  - [x] http://docs.python-cerberus.org/en/stable/
  - [x] http://docs.python-cerberus.org/en/latest/

- I consulted these sections of the docs:
  - API

- [x] I found the relevant problem in the docs.

- [x] I have the capacity to improve the docs when my problem is solved.
- [x] I have the capacity to submit a patch when a bug is identified.

----

#### Use-case abstract

Studying the API docs.

----

#### Support request / Bug report

the [latest API](http://docs.python-cerberus.org/en/latest/api.html) is missing the `Validator`'s docstring which documents the init-arguments. i will look into it, but need this reminder.

**Comment by nicolaiarocci** [comment]
👍

**Comment by funkyfuture** [comment]
fixed in #247
