### ISSUE TITLE
Having a `ValidatorBase` in version 1?

### ISSUE THREAD

**Issue by funkyfuture** [nicolaiarocci/cerberus#249]
- [x] I have the capacity to submit a patch if a solution is identified.

----

#### Use-case abstract

Implementing a custom validator w/o the default rules and types.

----

#### Proposal

in the light of #144 i had the thought that it may be a good idea to provide a `ValidatorBase` that contains the whole processing logic. such would be useful if one wanted to make a custom validator and disable a certain rule or type without replacing it. it seems both, simple to implement and easy to use.

on the other hand, this isn't a granular use at all and reusing desired rules/types would be cumbersome too. thus, metaprogramming may eventually be the best solution.

also, one must keep in mind that some rule-methods are depending on others.

**Comment by nicolaiarocci** [comment]
> on the other hand, this isn't a granular use at all and reusing desired rules/types would be cumbersome too (..) also, one must keep in mind that some rule-methods are depending on others.also, one must keep in mind that some rule-methods are depending on others.

Agreed. I think a ValidatorBase be seldom used, if at all.
