### ISSUE TITLE
Ability to use a different schema for unknown fields with property names matching a pattern/regex

### ISSUE THREAD

**Issue by ThatsGobbles** [nicolaiarocci/cerberus#253]
I'm using Cerberus to validate tags for metadata. I have a few fields that must be present (e.g. "author", "title", etc), but many other fields are user definable, so I plan to use unknown fields with a string schema to support this. However, it'd be quite nice to be able to be able to say somehow "any unknown fields that look like '*_date' should be checked as datetimes instead of strings". Perhaps a regex on the field name could accomplish this?

**Comment by funkyfuture** [comment]
looks like a use for an of-rule and `keyschema`.

it'd be appreciated if you added a usage example to the docs.

**Comment by ThatsGobbles** [comment]
Thanks for the response, @funkyfuture.

I admit, I'm new to the Cerberus discussions (and GitHub in general). Is there a specific format for sure a usage example? And where would be best to add said usage example?

**Comment by funkyfuture** [comment]
there's yet no documentation page for more complex uses. so, yours would be the first one. certainly a didactical useful.

if you're not familiar with restructuredtext ye, you would also have to dive into this.

if you posted a concrete usage example with a solution here i would review and format it. as i'm partly responsible for the code as it is, i'm always interested in insight how well a design and the documentation is. so, don't hesistate if something is unclear, it's highly appreciated feedback.

oh, when i mentioned `keyschema`, i referred to the 1.0 release candidate. before that rule had a different meaning. make sure you look at the on the [latest documentation](http://docs.python-cerberus.org/en/latest/).
