### ISSUE TITLE
Add ability to use `rename` in conjunction with other validate handlers

### ISSUE THREAD

**Issue by derek-miller** [nicolaiarocci/cerberus#260]
The `rename` handler fails when validating a document. For example:

```python
>>> import cerberus
>>> validator = cerberus.Validator(schema={'x': {'rename': 'y'}})
>>> assert validator.validate({'x': 1}), validator.errors
Traceback (most recent call last):
  File "<path>", line 3, in <module>
    assert validator.validate({'x': 1}), validator.errors
AssertionError: {'y': ['unknown field']}
```

It does work properly when using the `normalized()` function, however that means a user has to create two separate schemas; one for validating and one for normalizing. It would be nice to either ignore the `rename` handler when validating so it can be separately normalized with the same schema or support renaming during validation.

**Comment by funkyfuture** [comment]
you can either set `allow_unknown` or define the `y`-field in the schema.

**Comment by derek-miller** [comment]
@funkyfuture since the renaming happens first you would have to define the validation schema for `y` **and** the rename handler schema for `x` **and** pass `allow_unknown=True`. Seems a bit clunky to me. I am willing to implement a fix if you want this to be supported as a first class feature of the validate method. Otherwise it at least deserves a note in the documentation.

**Comment by funkyfuture** [comment]
no, either allow_unknown must be set or the field must be defined. otherwise there's a bug.

what do you propose to change?

**Comment by derek-miller** [comment]
Then there is a bug. See below:

Bug case:
```python
>>>import cerberus
>>> validator = cerberus.Validator(schema={'x': {'type': 'string', 'rename': 'y'}}, allow_unknown=True)
>>> assert validator.validate({'x': 1}), validator.errors  # passes even though x is an int
```

Currently the only way to rename and validate the field (this is what I described in my above comment):
```python
>>> import cerberus
>>> validator = cerberus.Validator(schema={'y': {'type': 'string'}, 'x': {'rename': 'y'}}, allow_unknown=True)
>>> assert validator.validate({'x': 1}), validator.errors
Traceback (most recent call last):
  File "<path>", line 3, in <module>
    assert validator.validate({'x': 1}), validator.errors
AssertionError: {'y': ['must be of string type']}
```

What I am proposing is there should be a way to not have to pass `allow_unknown=True` and validate the dict in one of two ways:
1) Skip renaming during validation so the user can separately normalize a document with one schema definition per field (not ideal but it is better than the current situation)
2) Support renaming during validation by updating the renamed fields in the schema (preferred)

**Comment by funkyfuture** [comment]
both your snippets work as expected.

1) that is: `validate(document, schema, normalize=False)`
2) explicit is better than implicit. your proposal seems prone to unwanted side-effects.

**Comment by derek-miller** [comment]
Really sucks there is no way to normalize and validate a document with a single schema without the use of allow/purge unknown.

I spent a little bit of time looking into what it would require to add a 'rename_order' option that worked as a class level option (and as a subschema option like 'purge_unknown') so the code could stay backwards compatible and fix this nuance. However since the normalize code generates validators for nested schemas (unlike the validation code) it makes this difficult. The only way I got this to worked seemed very hacky and I was not happy with it.

@funkyfuture I can send a PR if you are interested in looking at my proposed solution/fixing this nuance and I would be happy to help. Otherwise I will just continue on writing separate rename and validation schemas :(

**Comment by funkyfuture** [comment]
hm, the whole normalization-thing was added as small functionality to `coerce` values and matured by adjusting the code to meet failed user expectations (rightly).

imho, before hacking more into it, it would be a good idea to have an idea what this is eventually to be. thus, i would recommend to lay down the designated functionality and architecture changes (incl. #266). and discuss these. this may be flanked by implementation proposals.

and please, when posting examples use indentation for mappings to make it readable.

**Comment by funkyfuture** [comment]
actually. i like the idea of having a seperate normalization and validation schema. maybe the functionalities should also be seperated in different processort classes.

**Comment by derek-miller** [comment]
Yeah that is fair. It is just my current situation involves very large and complicated schemas so this only doubles the complexity for maintaining them but this is fine.
