### ISSUE TITLE
Proposal for a more flexible customization framework

### ISSUE THREAD

**Issue by funkyfuture** [nicolaiarocci/cerberus#276]
this is a very first draft for a proposal to change the way rules are defined. it emphasises the variety of rules and aims to provide an abstract framework that allows the user to amend and alter rules in a simple way while the code adapts its processing accordingly.

first, rules are not simply callables that are evaluated by more or less hardcoded behaviour, they are defined by these properties:

- processor
  - the implemented rule logic
  - callable with signature: validator, field, value
- succeeds
  - the rule will be processed after these
  - tuple of rule names
  - default: ()
- mandatory
  - the rule is evaluated, regardless its presence in the schema
  - bool
  - default: False
  - excludes properties: passive
- passive
  - is not evaluated actively, provides definitions for other rules
  - bool
  - default: False
  - excludes properties: breaking, modifying, traversing, traverse_at
- modifying
  - marks that the rule possibly returns a modified value
  - bool
  - default: False
  - excludes properties: breaking, passive, traversing, traverse_at
- breaking
  - if the rule returns True, the field will not be examined further in the current rule group
  - bool
  - default: False
  - excludes properties: modifying, passive, traversing, traverse_at
- traversing
  - the rule contains rules for subdocuments
  - bool
  - default: False
  - excludes properties: breaking, modifying, passive, traverse_at
- group_terminating
  - for pseudo-rules that terminate a rule group (e.g. normalize)
  - bool
  - default: False
  - exludes all properties but succeeds and traverse_at
- traverse_at
  - determines if and when traversing rules are evaluated within a group
  - '', 'start', or 'end'
  - default: ''
  - must be provided if group_terminating is True or not at all

though this is a long list and seems over-engineered, it describes what we have atm and only few of the properties must be defined for an actual instance. here are some examples:

```python
class Validator(BareValidator):  # BareValidator holds all the processing logic, but no rules
    @cerberus.rule(succeeds='type', modifying=True, traversing=True)
    def schema(self, definition, field, value, group):
        ...

    @cerberus.rule(breaking=True)
    def readonly(self, definition, field, value):
        ...

    @cerberus.rule(succeeds='readonly', modifying=True)
    def default(self, default_value, field, value):
        ...

    @cerberus.rule(succeeds='coerce', group_terminating=True, traverse_at='begin')
    def normalize():  # name is okay if the actual method follows this code?
        raise RuntimeError("Don't call me!")

    @cerberus.rule(succeeds='normalize', breaking=True)
    def nullable(self, definition, field, value):
        ...

    @cerberus.rule(succeeds=('schema', ...), group_terminating=True, traverse_at='end')
    def validate():
        raise RuntimeError("Don't call me!")
```

with this decorator notation rules will be stored in named tuples during parsing by that decorator. the downside is that there can only be one variant per rule name in the whole interpreter context.
alternatively, the rules would be implemented in functions and then be referenced in a class property. that would also allow a property to define inherited rules that are to be dropped.
rule_groups, rules_sequences and traversing_rules are class properties that are constructed according to the properties of all rules by the metaclass.

here's a prototype of an abstract evaluation logic:

```python
def evaluate(self, rule, field, *args):
    # get callable by rule
    # get constraint from schema
    # get value from document
    # invoke callable with self, constraint, field, value, *args
    # return its result


def process(self, *groups):
# substitutes __normalize mapping and __validate_definitions
    for group in self.rule_groups:
        if not groups.get(groups, True):
            continue
        aborted_fields = set()
        if self.traverse_at[group] == 'start':
            traverse(group)
        for rule in self.rules_sequences[group]:
            for field in set(document) - aborted_fields:
                if rule not in schema[field] or not rule.is_mandatory:
                    continue
                result = evaluate(rule, field)
                if group.is_modifying and rule.is_modifying:
                    document[field] = result
                elif rule.is_breaking and result is True:
                    aborted_fields.add(field)
        if self.traverse_at[group] == 'end':
            traverse(group)


def traverse(self, group):
    for rule in traversing_rules:
        for field in self.document:
            if rule not in self.schema[field]:
                continue
            result = evaluate(rule, field, group)
            if group.is_modifying:
                self.document[field] = result
```

for legacy, the metaclass would still look for methods named `_validate_<rule name>` and assign the default properties to such rule.

i'll amend this post with references to issues that would benefit from it.

**Comment by nicolaiarocci** [comment]
You clearly put a lot of thought into this one and I thank you for that. I do not feel like we should upgrade the API however. v1.0 is just out of the box and I feel it is powerful and bold enough to properly handle most use cases. The risk of over-engineering is, indeed, right behind the corner.

**Comment by funkyfuture** [comment]
in case someone might come back to this issue:

the above contains errors, of course. but the main point about it is: it suggests a framework. cerberus is 'just' a library, a very expandable though. but pushing that to its extreme would better be implemented from scratch.
