### ISSUE TITLE
`readonly` validation should happen before any other validation

### ISSUE THREAD

**Issue by pmdarrow** [nicolaiarocci/cerberus#63]
Currently, when a field is marked as readonly and has a custom validation rule, that validation rule gets executed before `readonly` is checked. Ideally, if `'readonly': True` is provided, that should happen before any other validation since it's pointless to validate a value that isn't allowed.

**Comment by nicolaiarocci** [comment]
Procedurally correct. Would you please elaborate on what is the point of setting up a custom validation rule for a read-only field (which would then be rejected before the custom rule is evaluated anyway)?

**Comment by nicolaiarocci** [comment]
thanks! Should be fixed now.
