### ISSUE TITLE
Proposal: Validation of dictionary-keys

### ISSUE THREAD

**Issue by funkyfuture** [nicolaiarocci/cerberus#83]
unless i overlooked something, it is not possible to validate the dictionary-keys of a document respectively a dictionary in it. with `jsonschema` this is done with the `patternProperties`. also, the key-types should be validatable.

it should be enough to enable checks for dicts:
```python
>>> v = Validator({'type': 'dict', 'propertyschema': {'type': 'string', 'regex': '^[a-zA-Z]$'}})
>>> v.validate({'mapping': {'foo': 'bar'}})
True
>>> v.validate({'mapping': {'foo_bar': 'foobar'}})
False
>>> v.validate({'mapping': {1: 2}})
False
>>> v.schema = {'type': 'dict', 'propertyschema': {'type': 'int', 'min': 0, 'max': 9}}
…
```

and one can trick to check the document's top-level-properties, which would be worth to be noted imo:
```python
>>> v.validate('document': document)
```

though i'm not very happy with the term `keyschema` as of now, because it's confusing; from a pythonic point of view, `valueschema` is much less ambigious, imo.

if there is a consent regarding the schema-design, i *may* be going to implement this.

**Comment by nicolaiarocci** [comment]
Let's see if others have [opinions to share](https://twitter.com/nicolaiarocci/status/592611546624368640) on this. 

> though i'm not very happy with the term `keyschema` as of now, because it's confusing; from a pythonic point of view, `valueschema` is much less ambigious, imo.

Yes `keyschema` never really convinced me...`valueschema` sounds good, although we should deprecate the former since a *lot* of people are using it in production already.

**Comment by funkyfuture** [comment]
to clarify, these are two issues:

----
- the validation of (json:) properties / (python:) keys
  - i would handle this with the term 'property' / 'properties', thus `propertiesschema`
    - not really pythonic
    - is there something clearer?

----
- renaming `keyschema` to `valueschema`
  - makes the terminology more pythonic and unambigious in that way
  - `keyschema` will be an alias for `valueschema`
    - should somehow yell out, that it is deprecated
    - assuming that client code is tested, it could even raise an exception; that may be a step in a later major release
  - the sooner the better
