### ISSUE TITLE
Allow a linelength of 120 chars?!

### ISSUE THREAD

**Issue by funkyfuture** [nicolaiarocci/cerberus#88]
i'm really much for pep8-compliance. however i think that nowadays there's hardly a need to restrict line-length to 80 characters. which also results in rather worse readable code due to lots of line-continuations.

what about setting the allowed line-length to 120 characters?

**Comment by nicolaiarocci** [comment]
We're not going to amend PEP8. Also, my regular workflow is 2 split panels in vim, each 80 characters wide :smile:

**Comment by rs** [comment]
http://youtu.be/wf-BqAjZb8M

I propose to open tipjar to offer you a bigger screen so you can fit more columns in your vim ;)

**Comment by nicolaiarocci** [comment]
haha actually I loved that RH talk. No kidding I've been coding on a 15" laptop screen forever :laughing:
