### ISSUE TITLE
Proposal: Propose possible value in case of unallowed key 

### ISSUE THREAD

**Issue by funkyfuture** [nicolaiarocci/cerberus#90]
ciao,

i'm thinking of adding a fuzzy string-matcher to extend the error message with a proposal which refers to an allowed key here: https://github.com/nicolaiarocci/cerberus/blob/master/cerberus/cerberus.py#L274

has anyone thoughts on how to opt-in/-out? should that behaviour be default? shall it be set per validator or per validation?

**Comment by nicolaiarocci** [comment]
Can you provide a practical example of how this would work?

**Comment by funkyfuture** [comment]
instead of `unknown field`, it would output something like

    `hosts` is an unknown field; did you mean `host`?

meanwhile i figured out that this must happen per validation to cover sub-schemas. 

the generic fuzzy-matching would rely on [`difflib.SequenceMatcher.ratio`](https://docs.python.org/2/library/difflib.html#difflib.SequenceMatcher.ratio).

another aspect i'm thinking about is the possibility to provide a mapping of allowd values to possible mistakes to cover more deviant proposals, let's say like `{'host': ['domain', 'domains']}.

**Comment by nicolaiarocci** [comment]
Cool stuff. The standard library never ceases to amaze me. 

> has anyone thoughts on how to opt-in/-out? should that behaviour be default? 

Since I imagine this would have an impact on overall performance, I would say that it should be opt-in/-out and probably disabled by default.

**Comment by funkyfuture** [comment]
tbc in #93
