### ISSUE TITLE
Allow to pass error-handlers to a `Validator`-instance

### ISSUE THREAD

**Issue by funkyfuture** [nicolaiarocci/cerberus#93]
this is a follow-up to #89 and #90.

i propose to introduce error-handlers in order to allow to deal with errors more flexible.

to achieve that:

- `Validator.__init__` takes an optional `error_handler`-object
- `Validator._error` is extended, so it stores the following data about an error:
  - `trail` - a list that represents the path to the `field` in the document (eg: `['a_dict', 'a_list']`); a common prefix can be specified upon calling `Validator.validate`
  - `field`, `value` - as of now
  - `constraint` - the constraint that failed
  - `message` - a simple error message, like currently implemented
- `Validator.errors` calls the `format`(?)-method of `error_handler` that may return errors in a desired format and / or do whatever its purpose is

there will be one default-handler and two as reference-implementations:

- `BasicErrorHandler`
  - returns errors as now
  - but concentates `trail` and `field`

- `HumanReadableErrorHandler`
  - is targeted to end-users
  - concentates `trail` and `field`
  - [suggests valid keys](https://github.com/nicolaiarocci/cerberus/issues/90), in case of an unallowed value
  - the index of list-items is increased by one
  - list-items are prefixed with `item #`

- `YamlErrorHandler`
  - structures errors in a dictionary
  - joins it into a yaml-file

**Comment by funkyfuture** [comment]
i'm willing to implement this, but will complete other TODOs before. any feedback is appreciated.

**Comment by CD3** [comment]
I think this is a great idea. I am using YAML to display error messages in my application, it is just a lot simpler to see what the problem is.

**Comment by nicolaiarocci** [comment]
Like it. Scheduling for 0.10 release.

**Comment by funkyfuture** [comment]
i'm currently working on that whenever i have the time and hope to provide a peek on wip this week (next week i'll be abroad).
considering how much unreleased changes currently cumulated and the amount of changes the error-handling will introduce, i'd say it'd be a good idea to postpone this to a `0.11`-release.

**Comment by funkyfuture** [comment]
closing this as the core interface is now available.

**Comment by Prudhvee** [comment]
Is `HumanReadableErrorHandler` implemented? Couldn't find the documentation.
