### ISSUE TITLE
Proposal: allow explicit rules per type

### ISSUE THREAD

**Issue by funkyfuture** [nicolaiarocci/cerberus#96]
atm it is possible to test a value to be one of multiple types, eg:

    'some_field': {'type': ['a_type', 'b_type']}

for simple cases this is fine. however:

- in case it's a `dict`, you can't test `schema` if `list` is also allowed
- any other rule can only be same for each possible type
- schema-definitions become more or less unclear:

```
{'a_field': {'type': ['dict', 'list', 'string'],
             'schema': {'type': ['dict', 'string'],
                        'regex': 'foo.*',
                        'keyschema': {'type': 'string',
                                      'regex': '.*'}},
             'keyschema': {'type': 'string',
                           'regex': '.*'},
             'regex': 'foo.*'}}
```

so, i propose to extend and also allow this notation:
```
{'a_field': {'type': {'dict': {'keyschema': {'type': 'string', 'regex': '.*'}},
                      'list': {'schema': {'type': {'dict': {'keyschema': {'type': 'string', 'regex': '.*'}},
                                                   'string': {'regex': 'foo.*'}}}},
                      'string': {'regex': 'foo.*'}}}}
```

so, allowed types can also be mappings whose value is a schema that will be validated against `value` if the key is recognized as valid type of `value`. thus (not in the example), rules could be very different depending on the actual type. it seems quiet easy to implement and shouldn't break anything.

though that idea came up while debugging as a more-or-less-workaround at first, i still find it's not a bad idea. imo, its sexyness is caused by its [explicit nature](https://www.python.org/dev/peps/pep-0020/). atm i don't need it, but that may change any moment.

**Comment by nicolaiarocci** [comment]
I like this. I'm wondering however wether allowing both type definitions would cause confusion. Quoting from the Zen of Python:

> There should be one-- and preferably only one --obvious way to do it.

One thought is that we could replace the current support for multiple field types (which has not been released yet) with this one. One issue would be that for simple fields, say a `string` with no rules other than type enforcement, you would be forced to pass either an empty ruleset (`{}`) or `None`. Hmm.

**Comment by funkyfuture** [comment]
good point.

i think it wouldn't be much of a problem to also handle rule-less strings.

but as a first step, schema-validation would have to invalidate any schema that has a `type`-rule with multiple values and other sibling-rules.

and something like this wouldn't match the dry-principle if forced to explicit per-type-rules:

    schema = {'property': {'type': ['string', 'number'], 'nullable': True}}

    schema = {'property': {'type': ['string': {'nullable': True}, 'number': {'nullable': True}]}

**Comment by nicolaiarocci** [comment]
Yeah both syntaxes have a place I guess. If we go this way, then the documentation should explain why both formats exist, and provide examples of why/when one is to be preferred to the other.

**Comment by CD3** [comment]
#112 comes close to this, you would just have to repeat the `type` keyword

```
{'a_field': {'anyof': {'type' : 'dict', 'keyschema': {'type': 'string', 'regex': '.*'}},
                      {'type' : 'list', 'schema': {'type': {'dict': {'keyschema': {'type': 'string', 'regex': '.*'}},
                                                   'string': {'regex': 'foo.*'}}}},
                      {'type' : 'string', 'regex': 'foo.*'}}}}
```

**Comment by funkyfuture** [comment]
agreed, just put a `solves #96` into your commit-message to auto-close this issue on merge.

i think such use-case would also be a good example for the end-user-documentation.
